from __future__ import annotations

import re
import sys
import unittest
from html.parser import HTMLParser
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
PROTOTYPE_ROOT = REPO_ROOT / "prototype"
sys.path.insert(0, str(PROTOTYPE_ROOT / "tests"))

from test_prompt_2c import CREATE_SIGN_HARNESS, node_json  # noqa: E402


class ElementCollector(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.elements = []

    def handle_starttag(self, tag, attrs) -> None:
        self.elements.append((tag, dict(attrs)))

    def by_id(self, element_id: str):
        return next(
            (attrs for _tag, attrs in self.elements if attrs.get("id") == element_id),
            None,
        )


class Prompt3CreateSignStaticTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.html = (PROTOTYPE_ROOT / "create-sign.html").read_text(encoding="utf-8")
        cls.script = (PROTOTYPE_ROOT / "create-sign.js").read_text(encoding="utf-8")
        cls.css = (PROTOTYPE_ROOT / "styles.css").read_text(encoding="utf-8")
        cls.parser = ElementCollector()
        cls.parser.feed(cls.html)

    def test_upload_and_url_are_the_only_exclusive_input_modes(self) -> None:
        modes = [
            attrs
            for tag, attrs in self.parser.elements
            if tag == "input" and attrs.get("name") == "reference_input_mode"
        ]
        self.assertEqual([item.get("value") for item in modes], ["upload", "url"])
        self.assertIn("checked", modes[0])
        self.assertNotIn("checked", modes[1])
        self.assertNotIn("hidden", self.parser.by_id("upload-source-panel"))
        self.assertIn("hidden", self.parser.by_id("url-source-panel"))
        self.assertNotIn("disabled", self.parser.by_id("reference-video"))
        self.assertIn("disabled", self.parser.by_id("direct-video-url"))
        self.assertEqual(self.parser.by_id("direct-video-url").get("type"), "url")
        self.assertEqual(self.parser.by_id("direct-video-url").get("autocomplete"), "off")
        self.assertEqual(self.parser.by_id("use-demo-video").get("type"), "button")
        self.assertNotRegex(self.html, r'name="reference_input_mode"[^>]+value="demo"')

        for behavior in (
            "syncReferenceInputMode",
            'uploadSourcePanel.hidden = state.inputMode !== "upload"',
            'urlSourcePanel.hidden = state.inputMode !== "url"',
            'fileInput.disabled = state.inputMode !== "upload"',
            'directVideoInput.disabled = state.inputMode !== "url"',
            'fetch("/api/runs/url"',
            'fetch("/api/runs/upload"',
            'fetch("/api/runs/demo"',
        ):
            self.assertIn(behavior, self.script)

    def test_reference_review_evidence_and_progressive_disclosure_are_preserved(self) -> None:
        for copy in (
            "Review the sign reference",
            "Reference review complete",
            "We found a few moments worth checking before creating the family materials.",
            "Review recommended",
            "Choose one or two reference poses",
            "Select the clearest moments to guide the visual.",
            "Tracking coverage",
            "Shows where the reference pose and main hand were visible across the video.",
            "Gaps help you decide whether to use tracked poses or choose clearer reference frames.",
            "Hand movement path",
            "Shows how the main hand moved relative to the body.",
            "Use it to compare movement direction and identify stable moments for visual preparation.",
        ):
            self.assertIn(copy, self.html)
        self.assertNotIn("open", self.parser.by_id("technical-details"))
        self.assertNotIn("open", self.parser.by_id("illustrative-technical-details"))
        self.assertIn("TRACKED_POSE_MINIMUM_PERCENT = 90", self.script)

    def test_illustrative_preview_is_truthful_optional_and_non_blocking(self) -> None:
        for copy in (
            "Family materials",
            "Baby Sign video tutorial",
            "This illustrative video was prepared separately with Google Labs / Gemini. It is not generated automatically from the current reference review.",
            "A short visual guide families can use before practising the sign during an everyday routine.",
            "Pre-generated demo asset",
            "Prepared separately from this reference review",
            "Not generated by this MediaPipe run",
            "Not automatically driven by current landmark coordinates",
            "Demo only",
            "Human review required",
            "Not linguistically certified",
            "Video tutorial not available yet.",
            "Use the Flashcard or Routine Card instead.",
            "Next product milestone",
            "Connect reviewed MediaPipe hand and pose landmarks to a reusable KinderFlow avatar",
            "See supporting materials",
        ):
            self.assertIn(copy, self.html)
        for forbidden in (
            "Generated from landmarks",
            "Landmark-generated video",
            "Final avatar",
            "Validated animation",
            "Certified sign video",
            "Published sign video",
            "Production output",
        ):
            self.assertNotIn(forbidden, self.html)
        self.assertNotIn("mas.mp4", self.html + self.script)
        self.assertNotIn("ayuda.mp4", self.html + self.script)
        self.assertNotIn("leche.mp4", self.html + self.script)
        self.assertIn(
            "Usage status unavailable; do not display externally",
            self.script,
        )
        self.assertRegex(
            self.html,
            re.compile(
                r'id="review-section".*id="visual-preparation-section".*id="visual-review-section".*id="illustrative-motion-section".*id="downstream-section"',
                re.DOTALL,
            ),
        )
        self.assertIn(".illustrative-motion-card", self.css)
        self.assertIn(".reference-input-choice", self.css)

    def test_demo_output_endpoint_is_never_a_reference_input(self) -> None:
        request_run = self.script.split("const requestRun = async (selection) => {", 1)[1].split(
            "form.addEventListener", 1
        )[0]
        self.assertNotIn("illustrative-videos", request_run)
        render_preview = self.script.split("const renderIllustrativeVideo = () => {", 1)[1].split(
            "const ROUTE_COPY", 1
        )[0]
        self.assertNotIn("/api/runs/", render_preview)


class Prompt3CreateSignBehaviorTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.runtime = node_json(
            CREATE_SIGN_HARNESS,
            PROTOTYPE_ROOT / "create-sign.js",
        )

    def test_url_mode_and_demo_shortcut_keep_one_active_source(self) -> None:
        url = self.runtime["urlMode"]
        self.assertEqual(url["source"], "url")
        self.assertEqual(url["inputMode"], "url")
        self.assertTrue(url["uploadHidden"])
        self.assertTrue(url["uploadDisabled"])
        self.assertFalse(url["urlHidden"])
        self.assertFalse(url["urlDisabled"])
        self.assertFalse(url["runDisabled"])

        demo = self.runtime["demoShortcut"]
        self.assertEqual(demo["source"], "demo")
        self.assertEqual(demo["inputMode"], "upload")
        self.assertEqual(demo["sign"], "MORE")
        self.assertTrue(demo["signDisabled"])
        self.assertEqual(demo["directUrl"], "")
        self.assertFalse(demo["uploadHidden"])
        self.assertTrue(demo["urlHidden"])

    def test_missing_video_clears_media_and_keeps_static_flow_available(self) -> None:
        missing = self.runtime["missingIllustrative"]
        self.assertEqual(missing["videoSrc"], "")
        self.assertTrue(missing["availableHidden"])
        self.assertTrue(missing["missingVisible"])
        self.assertTrue(missing["disclosureHidden"])
        self.assertTrue(missing["technicalHidden"])
        self.assertTrue(missing["visualPreparationStillAvailable"])

    def test_new_reference_clears_media_and_pending_submit_locks_identity(self) -> None:
        reset = self.runtime["fullReset"]
        self.assertEqual(reset["illustrativeSrc"], "")
        self.assertTrue(reset["illustrativePaused"])

        pending = self.runtime["inFlightGuard"]
        self.assertEqual(pending["fetchDelta"], 1)
        self.assertTrue(pending["pending"])
        self.assertEqual(pending["source"], "url")
        self.assertEqual(pending["inputMode"], "url")
        self.assertEqual(pending["sign"], "HELP")
        self.assertTrue(pending["modeControlsLocked"])
        self.assertTrue(pending["signLocked"])
        self.assertTrue(pending["routineLocked"])
        self.assertTrue(pending["urlLocked"])
        self.assertTrue(pending["demoLocked"])


if __name__ == "__main__":
    unittest.main()
